name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          - Windows
          - MacOs
        py:
          - "3.11"
          - "3.10"
          - "3.9"
    steps:
      - uses: actions/checkout@v2
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Install dependencies
        run: |
          poetry update
          poetry run pip install --upgrade setuptools
          poetry install
          poetry run pyproj sync --area-of-use=Canada
      - name: Run tests
        run: poetry run pytest
